---
api_key:
  description: "API key"
  type: "string"
  secret: true
  required: true
api_root:
  description: "API Root"
  type: "string"
  secret: false
  required: true
ssl_verify:
  description: "Should the SSL certificate be verified when connecting over TLS"
  type: boolean
  secret: false
  required: true